/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'davor' at '6/10/16 11:31 AM' with Gradle 2.12
 *
 * @author davor, @date 6/10/16 11:31 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
